// Code generated by devtool; DO NOT EDIT.
package client

const (
	// Version is the version of client.
	Version = "0.0.1"

	// GoVersion declares what version of Go should be used.
	GoVersion = "1.17.2"
)
